version: "3.8"

services:
  psqldb:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $PSQLDB_PASSWORD
  app:
    depends_on:
      - psqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
